---
title: "01b-pkg-infor"
author: "Danyang Dai"
date: "29/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(glue)
library(feasts)
library(cranlogs)
library(plotly)
library(scales)
library(lubridate)
knitr::opts_chunk$set(
  cache = TRUE,
  cache.path = "cache/"
)
```

```{r}
library(DBI)

con <- dbConnect(
  RPostgres::Postgres(),
  host = Sys.getenv("cranloghost"),
  dbname = "cranlogs",
  user = "guest",
  password = Sys.getenv("cranlogpw")
)

DBI::dbListTables(con)
#> [1] "cran_logs"
cran_logs <- tbl(con, "cran_logs")

# cran_logs %>%
#   filter(package %in% c("rmarkdown", "shiny")) %>%
#   collect() %>%
#   pivot_longer(c(n_unique, n_total)) %>%
#   ggplot(aes(x = date, y = value, colour = name)) +
#   geom_line() +
#   scale_y_log10() +
#   facet_grid(vars(package))
```
 
 
```{r}
daily_total <- cran_logs %>%
  group_by(date) %>%
  summarise(total_unique = sum(n_unique), total_download = sum(n_total)) %>%
  collect() %>%
  mutate(across(c("total_unique", "total_download"), as.integer))



daily_total %>%
  pivot_longer(c(total_unique, total_download)) %>%
  ggplot(aes(x = date)) +
  geom_line(aes(y = value / 1000, colour = name))
```

From the graph above, it shows that 



```{r}
duplicated_date <- cran_logs %>%
  count(date,package) %>% 
  filter(n>1) %>% 
  count(date) %>% 
  collect %>% 
  mutate(across(c(n), as.integer))

cran_logs %>% 
  count(date,package) %>%
  filter(date == "2013-05-23") %>% 
  collect()

```


```{r}
cran_logs %>% 
  count(date,package) %>%
  filter(date == "2012-10-07") %>% 
  collect()
```

```{r}
processed_file <-  list.files(path = here::here("data/cranlogs_processed"), pattern=".csv.gz$",
                        full.names = TRUE) 
names(processed_file) <- str_remove(basename(processed_file),"\\.csv\\.gz$")

```

```{r}
# for (i in (1:3248)) {
#   cranlog_processed <- lapply(processed_file[i], read_csv)
#   output <- bind_rows(cranlog_processed, .id = "file")
#   tf <- output %>% 
#    count(date == file) 
#   if (tf$`date == file` == "TRUE"){
#      i <- i+1 
#    } else {
#     unmatch <-rbind(unmatch,output)
#     i <- i+1 }
# }

unmatch <- unmatch %>% 
  mutate(across(c("file"), as.Date)) %>% 
  filter(file != date)

unmatch_date <- unmatch %>% 
  count(file,date)

unmatch_pkg <- unmatch %>% 
  count(file,date,package)

```


```{r}
forecast_dupl_date <- forecast_download %>% 
  filter(duplicated(date))

forecast_dupl<- forecast_download %>% 
  filter(date %in% forecast_dupl_date$date)


unmatch_forecast <- unmatch %>% filter(package == "forecast")

unmatch_forecast %>% filter(date %in% forecast_dupl$date)
  

```

```{r}
cran_logs %>% 
  count(date,package) %>% 
  filter(n >1)
```



```{r}
matrixpls_dup <- matrixpls_download %>% 
 filter(duplicated(date))

matrixpls_download %>% 
  filter(date %in% c(matrixpls_dup$date))
```
```{r}
unmatch_matrixpls <- unmatch %>% filter(package == "matrixpls")

unmatch_matrixpls %>% filter(date %in% matrixpls_dup$date)
```

