---
title: "02b-rpkg-download-updates"
author: "Danyang Dai"
date: "31/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(rvest)
library(glue)
library(feasts)
library(cranlogs)
library(plotly)
library(scales)
```

```{r}
# adding the userR conference date
conference_dates <- tribble(
  ~name, ~date,
  "UseR", "2004-05-20",
  "UseR", "2006-06-15",
  "UseR", "2007-08-08",
  "UseR", "2008-08-14",
  "UseR", "2009-07-08",
  "UseR", "2010-07-20",
  "UseR", "2011-08-16",
  "UseR", "2012-06-12",
  "UseR", "2013-06-10",
  "UseR", "2014-06-30",
  "UseR", "2015-06-30",
  "UseR", "2016-06-27",
  "UseR", "2017-07-04",
  "UseR", "2018-07-10",
  "UseR", "2019-07-09",
  "UseR", "2020-07-07",
  "UseR", "2021-07-05",
  "RStudio", "2017-01-11",
  "RStudio", "2018-01-31",
  "RStudio", "2019-01-15",
  "RStudio", "2020-01-27",
  "RStudio", "2021-03-03",
)

UseR <- dplyr::filter(conference_dates, name == "UseR", date > "2013-01-01")
Rstudio <- dplyr::filter(conference_dates, name == "RStudio")
```


```{r}
# load in the data from the database
library(DBI)

con <- dbConnect(
  RPostgres::Postgres(),
  host = Sys.getenv("host"),
  dbname = "cranlogs",
  user = "guest",
  password = Sys.getenv("cranlogpw")
)

DBI::dbListTables(con)
#> [1] "cran_logs"
cran_logs <- tbl(con, "cran_logs")

same_logfile <- as.Date(c("2012-10-11","2012-10-13","2012-10-15"))

daily_total_pre2013 <- cran_logs %>%
  filter(!file_date %in% same_logfile) %>% 
  filter(file_date < "2013-01-01") %>% 
  group_by(date) %>% 
  summarise(total_unique = sum(n_unique), total_download = sum(n_total)) %>% 
  collect() %>%
  mutate(across(c("total_unique", "total_download"), as.integer))

daily_total_post2013 <- cran_logs %>%
  filter(file_date >= "2013-01-01") %>% 
  group_by(file_date) %>% 
  summarise(total_unique = sum(n_unique), total_download = sum(n_total)) %>% 
  collect() %>%
  mutate(across(c("total_unique", "total_download"), as.integer)) %>% 
  rename(date = file_date)

daily_total <- bind_rows(daily_total_pre2013,daily_total_post2013)

duplicate_dates <- daily_total$date[duplicated(daily_total$date)]

seq_date <- daily_total$date
range_date <- seq(min(seq_date), max(seq_date), by = 1)
range_date[!range_date %in% seq_date] 
```


```{r}
library(tsibble)

# there are three days of missing data. In order to fit models for later analysis, filled the missing data with the same date from 2013-01-01. The reason is that from 12-29 to 12-31 are all holiday seasons and use the new years day data as supplements

daily_total <- daily_total %>%
  add_row(date = as.Date("2012-12-31"), total_unique = 13676, total_download = 10911, .before = 90) %>%
  add_row(date = as.Date("2012-12-30"), total_unique = 13676, total_download = 10911, .before = 90) %>%
  add_row(date = as.Date("2012-12-29"), total_unique = 13676, total_download = 10911, .before = 90)
```


```{r}
daily_total %>%
  as_tsibble(index = date) %>%
  # fill_gaps() %>%
  model(
    STL(total_unique ~ trend() +
      season("week", window = "periodic"))
  ) %>%
  components() %>%
  autoplot() +
  geom_vline(
    xintercept = as.numeric(as.Date(Rstudio$date)), linetype = "dotted",
    color = "red", size = 0.1
  ) +
  geom_vline(
    xintercept = as.numeric(as.Date(UseR$date)), linetype = "dotted",
    color = "blue", size = 0.1
  )
```



```{r}
accum_downloads <- cran_logs %>%
  group_by(package) %>%
  summarise(accum_unique = sum(n_unique), accum_total = sum(n_total)) %>%
  collect() %>%
  mutate(across(c("accum_unique", "accum_total"), as.integer))

accum_downloads_unqie <- accum_downloads %>%
  arrange(accum_unique) %>%
  mutate(order = rep(1:21754))

top_100_unique <- accum_downloads_unqie[21654:21754, ]

total_unique <- sum(accum_downloads$accum_unique)
sum(top_100_unique$accum_unique) / total_unique
```

```{r}
accum_downloads_unqie %>%
  ggplot() +
  geom_point(aes(x = order, y = accum_unique))
```

From the plot we could see that majority of the packages has relatively low accumulated downloads. The top 100 packages constitute 47\% of the total unique downloads. 

```{r}
accum_downloads_total <- accum_downloads %>%
  arrange(accum_total) %>%
  mutate(order = rep(1:21754))


accum_downloads_total %>%
  ggplot() +
  geom_point(aes(x = order, y = accum_total))


top_100_total <- accum_downloads_total[21654:21754, ]

total_total <- sum(accum_downloads$accum_total)
sum(top_100_total$accum_total) / total_total
```
Same pattern can be found in the total downloads. The top 100 packages constitute 49\% of the total unique downloads. 




```{r}
load(here::here("data/derived/updates.Rdata"))
load(here::here("data/derived/updates_2.Rdata"))
load(here::here("data/derived/updates_3.Rdata"))
load(here::here("data/derived/updates_4.Rdata"))
load(here::here("data/derived/updates_5.Rdata"))
load(here::here("data/derived/updates_6.Rdata"))
load(here::here("data/derived/updates_7.Rdata"))
load(here::here("data/derived/updates_8.Rdata"))
load(here::here("data/derived/updates_9.Rdata"))

updates_list <- list(updates, updates_2, updates_3, updates_4, updates_5, updates_6, updates_7, updates_8, updates_9)

select_pkg_ver_date <- function(x) {
  x %>%
    dplyr::select(Package, Version, date)
}


updates_select <- map_dfr(updates_list, select_pkg_ver_date)

updates_select <- updates_select %>%
  mutate(Date = as.Date(updates_select$date))

saveRDS(updates_select, "../data/analysis/updates.RDS")

first_realse <- updates_select %>% 
  group_by(Package) %>%
  filter(date == min(date)) %>% 
  rename(package = Package)
```

```{r}
unique_2020 <- cran_logs %>% 
  filter(date >= "2020-06-01") %>% 
  filter(date <= "2021-06-01") %>% 
  group_by(date) %>% 
  summarise(daily_unique = sum(n_unique),
            daily_total = sum(n_total)) %>% 
  collect() %>% 
  mutate(across(c("daily_unique", "daily_total"), as.integer))

unique_2020 %>% 
  ggplot(aes(x=date,y=daily_unique/1000))+
  geom_line()

```


```{r}
# last year total downloads 

past_year_data <- cran_logs %>% 
  filter(date >= "2020-06-01") %>% 
  filter(date <= "2021-06-01") %>% 
  group_by(package) %>% 
  summarise(total_unique = sum(n_unique), total_download = sum(n_total)) %>% 
  collect() 
  
past_year_unique <- past_year_data %>% 
  arrange(total_unique) %>%
  mutate(order = rep(1:nrow(past_year_data))) %>% 


past_year_100 <- past_year_unique[21088:21188, ]

past_year_realse_unique <- past_year_100 %>%
  left_join(first_realse, by = "package") %>%
  ggplot(aes(x = Date, y = total_unique)) +
  geom_point(aes(label = package))

ggplotly(past_year_realse_unique, dynamicTicks = TRUE) %>%
  layout(hovermode = "x")
```

```{r}
past_year_bottom <- past_year_unique[1:5000, ]

 past_year_unique %>%
  left_join(first_realse, by = "package") %>%
  filter(Date <= "2019-06-30") %>% 
  arrange(total_unique) %>% 
  slice(1:1000) %>% 
  ggplot(aes(x = total_download, y = total_unique)) +
  geom_point(aes(label = package, color = total_download))+
  scale_color_viridis_c() +
  geom_abline(slope = 1, intercept = 0)+ 
  geom_smooth(method = "lm", formula = y ~ -1 + x )

ggplotly(past_year_realse_unique_bottom, dynamicTicks = TRUE) %>%
  layout(hovermode = "x")
```


```{r}
updates_select %>% 
  filter(Package %in% c(past_year_bottom$package)) %>% 
  count(Package) %>% 
  arrange(desc(n))

```

```{r}
# A function that does STL decomposition on all the packages 

cran_package <- function(pkg_name){
  # input pkg must be a character veriable 
  library(DBI)
  library(tidyverse)
  
  con <- dbConnect(
  RPostgres::Postgres(),
  host = Sys.getenv("cranloghost"),
  dbname = "cranlogs",
  user = "guest",
  password = Sys.getenv("cranlogpw")
)

  DBI::dbListTables(con)
  #> [1] "cran_logs"
  cran_logs <- tbl(con, "cran_logs")
  
  # same_logfile <- as.Date(c("2012-10-11","2012-10-13","2012-10-15"))
  # 
  # package_download_pre2013 <- cran_logs %>% 
  # filter(!file_date %in% same_logfile) %>% 
  # filter(file_date < "2013-01-01") %>% 
  # filter(package == pkg_name) %>% 
  # select(date,package,n_unique,n_total) %>% 
  # collect()
  # 
  package_download_post2013 <- cran_logs %>% 
  filter(file_date >= "2013-01-01") %>% 
  filter(package == pkg_name) %>% 
  group_by(file_date) %>% 
  summarise(unique = sum(n_unique),total = sum(n_total)) %>% 
  collect() %>% 
  rename(date = file_date) %>% 
  mutate(across(c("unique", "total"), as.integer))

  #package_download <- bind_rows(package_download_pre2013,package_download_post2013)

  return(package_download_post2013)
}
```

```{r}
update_pkg <- function(pkg_name){
  # pkg_name must be a character variable 
  library(tidyverse)
  update_date <- updates_select %>% 
  filter(Package == pkg_name ) %>% 
  select(Package, Version, Date)
  return(update_date)
}
```

```{r}
stl_update_unique <- function(pkg_downloads,updates){
  library(fabletools)
  pkg_date <- pkg_downloads$date
  date_range <- seq(min(pkg_date), max(pkg_date), by = 1)
  missing_date <- !date_range %in% pkg_date
  tf <- missing_date[missing_date == TRUE]
 # if( TRUE %in% tf){
 #   return(print("This package does not have continues data"))
 # }
 #  else{
 #    return(
  pkg_downloads %>%
  as_tsibble(index = date) %>%
  tsibble::fill_gaps(unique = 0) %>% 
  model(
    STL(unique ~ trend() +
      season("week", window = "periodic"))
  ) %>%
  components() %>% 
  autoplot() +
  geom_vline(
    xintercept = as.numeric(as.Date(updates$Date)), linetype = "dotted",
    color = "red", size = 0.5
  )
    
    
}

```


```{r}
ggplot_cranlog <- cran_package("ggplot2")
ggplot_update <- update_pkg("ggplot2")
stl_update_unique(ggplot_cranlog,ggplot_update)
```

```{r}
forecast_cranlog <- cran_package("forecast")
forecast_update <- update_pkg("forecast")
stl_update_unique(forecast_cranlog,forecast_update)
```

```{r}
dpcc_cranlog <- cran_package("dpcc")
dpcc_update <- update_pkg("dpcc")
stl_update_unique(dpcc_cranlog,dpcc_update)
```


```{r}
 dpcc_cranlog %>%
  as_tsibble(index = date) %>%
  tsibble::fill_gaps(unique = 0) %>% 
  model(
    STL(unique ~ trend() +
      season("week", window = "periodic"))
  ) %>%
  components() %>% 
  autoplot()
```


```{r}
top_100_unique %>%
  left_join(first_realse, by = "package") %>%
  arrange(date)
```

```{r}
realse_unique <- top_100_unique %>%
  left_join(first_realse, by = "package") %>%
  ggplot(aes(x = Date, y = accum_unique)) +
  geom_point(aes(label = package))



ggplotly(realse_unique, dynamicTicks = TRUE)

```







```{r}
top_100_total %>%
  left_join(first_realse, by = "package") %>%
  arrange(date)
```

```{r}
relase_total <- top_100_total %>%
  left_join(first_realse, by = "package") %>%
  ggplot(aes(x = Date, y = accum_total)) +
  geom_point(aes(lable = package))

ggplotly(relase_total, dynamicTicks = TRUE) %>%
  layout(hovermode = "x")
```

