---
title: "Dependency analysis"
author: "Danyang Dai"
date: "03/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#library(devtools)
#install_github("cbail/textnets")
#library(textnets)
library(ggraph)
library(pkgsearch)
library(fable)
library(feasts)
library(vars)
library(tidyverse)
library(MASS)
```

```{r}
url <- "http://cran.rstudio.com/web/packages/packages.rds"
db <- readRDS(url(url)) %>% 
  as.data.frame()%>% 
  mutate(Description = str_replace_all(Description, "\n", " "),
         Description = str_squish(Description),
         Title = str_replace_all(Title, "\n", " "))
```

```{r}
con <- dbConnect(
  RPostgres::Postgres(),
  host = "db.mitchelloharawild.com",
  dbname = "cranlogs",
  user = "guest",
  password = "JNoGzAc9V5yxdsU9"
)

DBI::dbListTables(con)
#> [1] "cran_logs"
cran_logs <- tbl(con, "cran_logs")
```


```{r}
# dependency analysis
depends <- sapply(strsplit(as.character(db$Depends), " \\("), "[", 1)
imports <- sapply(strsplit(as.character(db$Imports), " \\("), "[", 1)
cols_im <-  c("imp", "pkg")
cols <- c("dep", "pkg")
depends <- depends %>%
  as.data.frame() %>%
  mutate(pkg = db$Package)
imports <- imports %>%
  as.data.frame() %>%
  mutate(pkg = db$Package)

colnames(depends) <- cols
colnames(imports) <- cols_im

```

```{r}
pkg_wt_dep <- depends %>% 
  filter(dep != "R")

pkg_dep_dyp <- depends %>% 
  filter(dep %in% "dplyr")

name_dp <- c(pkg_dep_dyp$pkg)
```

```{r}
dep_dplyr <- cran_logs %>% 
  filter(package %in% name_dp) %>% 
  collect()

dplyr_db <-  cran_logs %>% 
  filter(package == "dplyr") %>% 
  collect()

updates_dep <-map_dfr(name_dp, cran_package_history)

updates_dep <- updates_dep %>% 
  select(Package,Version,Date)

updates_dplyr <- cran_package_history("dplyr")

updates_dplyr <- updates_dplyr %>% 
  select(Package,Version,date)
```


```{r}
dplyr_db <- dplyr_db %>% 
  group_by(file_date) %>% 
  summarise(n_unique = sum(n_unique),n_total = sum(n_total))

dplyr_db %>% 
  as_tsibble(index = file_date) %>% 
  model(STL(n_unique, robust = TRUE)) %>%
  components(season_adjust) %>% 
  autoplot()

adj_dplyr <- dplyr_db %>% 
  as_tsibble(index = file_date) %>% 
  model(STL(n_unique,robust = TRUE)) %>%
  components() %>% 
  dplyr::select(season_adjust)

adj_dplyr %>% 
  autoplot() +
   geom_vline(
    xintercept = as.numeric(as.Date(updates_dplyr$date)), linetype = "dotted",
    color = "red", size = 0.1
  )

```



```{r}
dep_dplyr <- split(dep_dplyr,dep_dplyr$package)
andromeda <- dep_dplyr[1]
bread <- dep_dplyr[2]
censusr <- dep_dplyr[3]
chunked <- dep_dplyr[4]
dplyr.teradata <- dep_dplyr[5]
ggraptR <- dep_dplyr[6]
shinySIR <- dep_dplyr[7]
tangram.pipe <- dep_dplyr[8]
ushr <- dep_dplyr[9]
```


```{r}
andromeda <- as_tibble(andromeda) 
andromeda <- andromeda$Andromeda
andromeda <- andromeda %>% 
  group_by(file_date) %>% 
  summarise(n_unique = sum(n_unique),n_total = sum(n_total))

andromeda %>% 
  as_tsibble(index = file_date) %>% 
  model(STL(n_unique, robust = TRUE)) %>%
  components(season_adjust) %>% 
  autoplot()

adj_andromeda <- andromeda %>% 
  as_tsibble(index = file_date) %>% 
  model(STL(n_unique, robust = TRUE)) %>%
  components() %>% 
  dplyr::select(season_adjust)


adj_andromeda %>% 
  autoplot()
```

```{r}
bread <- as_tibble(bread) 
bread <- bread$bread
bread <- bread %>% 
  group_by(file_date) %>% 
  summarise(n_unique = sum(n_unique),n_total = sum(n_total))

bread %>% 
  as_tsibble(index = file_date) %>% 
  model(STL(n_unique)) %>%
  components(season_adjust) %>% 
  autoplot()

adj_bread <- bread %>% 
  as_tsibble(index = file_date) %>% 
  model(STL(n_unique)) %>%
  components() %>% 
  dplyr::select(season_adjust)


adj_bread %>% 
  autoplot()
```



```{r}
censusr <- as_tibble(censusr) 
censusr <- censusr$censusr
censusr <- censusr %>% 
  group_by(file_date) %>% 
  summarise(n_unique = sum(n_unique),n_total = sum(n_total))

censusr %>% 
  as_tsibble(index = file_date) %>% 
  tsibble::fill_gaps() %>% 
  model(STL(n_unique)) %>%
  autoplot()

adj_censusr <- censusr %>% 
  as_tsibble(index = file_date) %>% 
  model(STL(n_unique)) %>%
  components() %>% 
  dplyr::select(season_adjust)


adj_censusr %>% 
  autoplot()
```

```{r}
ggplot <- cran_logs %>% 
  filter(package == "ggplot2") %>% 
  collect()


gganimate <-  cran_logs %>% 
  filter(package == "gganimate") %>% 
  collect()


ggcorrplot <-  cran_logs %>% 
  filter(package == "ggcorrplot") %>% 
  collect()

```


```{r}

gganimate <-  gganimate %>% 
  group_by(file_date) %>% 
  summarise(n_unique = sum(n_unique),n_total = sum(n_total)) 

gganimate <- gganimate %>% 
  group_by(file_date) %>% 
  summarise(n_unique = sum(n_unique),n_total = sum(n_total)) %>% 
  as_tsibble(index = file_date)

ggcorrplot <- ggcorrplot %>% 
  group_by(file_date) %>% 
  summarise(n_unique = sum(n_unique),n_total = sum(n_total)) %>% 
  as_tsibble(index = file_date)


ggplot <- ggplot %>% 
  group_by(file_date) %>% 
  summarise(n_unique = sum(n_unique),n_total = sum(n_total)) %>% 
  filter(file_date >= "2019-01-03") %>% 
  as_tsibble(index = file_date)


gganimate %>% 
  model(STL(n_unique,robust = TRUE)) %>%
  components(season_adjust) %>% 
  autoplot()

ggplot %>% 
  model(STL(n_unique,robust = TRUE)) %>%
  components(season_adjust) %>% 
  autoplot()

ggcorrplot %>% 
  model(STL(n_unique,robust = TRUE)) %>%
  components(season_adjust) %>% 
  autoplot()

adj_gganimate <- gganimate %>% 
  model(STL(n_unique,robust = TRUE)) %>%
  components() %>% 
  dplyr::select(season_adjust)


adj_ggplot <- ggplot %>% 
  model(STL(n_unique,robust = TRUE)) %>%
  components() %>% 
  dplyr::select(season_adjust)


ad_gg <- adj_gganimate %>% 
  mutate(ggplot = adj_ggplot$season_adjust)


adf_1<- adj_gganimate %>%
  as_tsibble() %>% 
  features(season_adjust, features = list(adf = ~ tseries::adf.test(.)$p.value))


adf_2 <- adj_ggplot %>%
  as_tsibble() %>% 
  features(season_adjust, features = list(adf = ~ tseries::adf.test(.)$p.value))

ad_gg <- adj_gganimate %>% 
  mutate(ggplot = adj_ggplot$season_adjust) %>% 
  rename(gganimate = season_adjust) %>% 
  as.data.frame() %>% 
  select(-file_date)

ad_gg_scale <- ad_gg %>% 
  mutate(ggplot = scale(ggplot),
         gganimate = scale(gganimate))

var_gg <- VAR(ad_gg, p = 2,type = "none")

fevd_gg <-fevd(var_gg, n.ahead = 7)

fevd <- array(NA,dim = c(2,2,7))

for (i in 1:7) {
  fevd[,,i] <- rbind(fevd_gg$gganimate[i,],fevd_gg$ggplot[i,])
}

spillover_gg <- c(rep(NA,7))

for(i in 1:7) {
  spillover_gg[i] <- 1-sum(diag(fevd[,,i]))/sum(fevd[,,i])
}


tibble(
  date = seq_along(spillover_gg),
  spillover = round(spillover_gg*100,2)) %>% 
  ggplot(aes(x = date, y = spillover)) + 
  geom_point() +
  theme_bw() 
```


```{r}

dep_pkg <-  cran_logs %>% 
  filter(package %in% !! pkg_wt_dep$pkg) %>% 
  group_by(package) %>% 
  summarise(n_unique = sum(n_unique),n_total = sum(n_total)) %>% 
  collect()
```

```{r}
lubridate <- cran_logs %>% 
  filter(package == "lubridate") %>% 
  collect()


lubridate <- lubridate %>% 
  group_by(file_date) %>% 
  summarise(n_unique = sum(n_unique),n_total = sum(n_total)) %>% 
  as_tsibble(index = file_date)

methods <- cran_logs %>% 
  filter(package == "methods") %>% 
  collect()


methods <- methods %>% 
  group_by(file_date) %>% 
  summarise(n_unique = sum(n_unique),n_total = sum(n_total)) %>% 
  as_tsibble(index = file_date) 


lubridate %>% 
  filter(file_date >= "2013-01-01") %>% 
  model(STL(n_unique,robust = TRUE)) %>%
  components(season_adjust) %>% 
  autoplot()

methods %>% 
  filter(file_date >= "2013-01-01") %>% 
  model(STL(n_unique,robust = TRUE)) %>%
  components(season_adjust) %>% 
  autoplot()


adj_gganimate <- gganimate %>% 
  model(STL(n_unique,robust = TRUE)) %>%
  components() %>% 
  dplyr::select(season_adjust)


adj_ggplot <- ggplot %>% 
  model(STL(n_unique,robust = TRUE)) %>%
  components() %>% 
  dplyr::select(season_adjust)


ad_gg <- adj_gganimate %>% 
  mutate(ggplot = adj_ggplot$season_adjust)


adf_1<- adj_gganimate %>%
  as_tsibble() %>% 
  features(season_adjust, features = list(adf = ~ tseries::adf.test(.)$p.value))


adf_2 <- adj_ggplot %>%
  as_tsibble() %>% 
  features(season_adjust, features = list(adf = ~ tseries::adf.test(.)$p.value))

ad_gg <- adj_gganimate %>% 
  mutate(ggplot = adj_ggplot$season_adjust) %>% 
  rename(gganimate = season_adjust) %>% 
  as.data.frame() %>% 
  select(-file_date)

var_gg <- VAR(ad_gg, p = 2,type = "none")

fevd_gg <-fevd(var_gg, n.ahead = 7)

fevd <- array(NA,dim = c(2,2,7))

for (i in 1:7) {
  fevd[,,i] <- rbind(fevd_gg$gganimate[i,],fevd_gg$ggplot[i,])
}

spillover_gg <- c(rep(NA,7))

for(i in 1:7) {
  spillover_gg[i] <- 1-sum(diag(fevd[,,i]))/sum(fevd[,,i])
}


tibble(
  date = seq_along(spillover_gg),
  spillover = round(spillover_gg*100,2)) %>% 
  ggplot(aes(x = date, y = spillover)) + 
  geom_point() +
  theme_bw() 
```





```{r}
dep_group <- depends %>%
  group_by(pkg) %>%
  slice(1L)
dep_cloud <- textnets::PrepText(dep_group, groupvar = "pkg", textvar = "dep", node_type = "groups", tokenizer = "words", pos = "nouns", remove_stop_words = TRUE, compound_nouns = TRUE)

dep_text_network <- CreateTextnet(dep_cloud)

VisTextNet(dep_text_network)

```