---
title: "Untitled"
author: "Danyang Dai"
date: "28/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# load in packages 

library(tidyverse)
library(lubridate)
library(cranlogs)
library(DBI)
library(rvest)

```


```{r}
# connect to the data base
con <- dbConnect(
  RPostgres::Postgres(),
  host = "db.mitchelloharawild.com",
  dbname = "cranlogs",
  user = "guest",
  password = "JNoGzAc9V5yxdsU9"
)

DBI::dbListTables(con)
#> [1] "cran_logs"
cran_logs <- tbl(con, "cran_logs")
```

```{r}
# duplicated downloads over time 

daily_download <- cran_logs %>% 
  group_by(file_date) %>% 
  summarise(download = sum(n_total),unique = sum(n_unique)) %>% 
  collect()


daily_download <- daily_download %>% 
  mutate(difference = download - unique) %>% 
  mutate(download = as.integer(download)) %>% 
  mutate(unique = as.integer(unique))


daily_download %>% 
  ggplot(aes(x = file_date)) +
  geom_line(aes(y = download), color = "red") + 
  geom_line(aes(y = unique), color = "blue") + 
  geom_line(aes(y = difference), color = "green")
```


```{r}
load(here::here("data/derived/updates.Rdata"))
load(here::here("data/derived/updates_2.Rdata"))
load(here::here("data/derived/updates_3.Rdata"))
load(here::here("data/derived/updates_4.Rdata"))
load(here::here("data/derived/updates_5.Rdata"))
load(here::here("data/derived/updates_6.Rdata"))
load(here::here("data/derived/updates_7.Rdata"))
load(here::here("data/derived/updates_8.Rdata"))
load(here::here("data/derived/updates_9.Rdata"))

updates_list <- list(updates, updates_2, updates_3, updates_4, updates_5, updates_6, updates_7, updates_8, updates_9)

select_pkg_ver_date <- function(x) {
  x %>%
    dplyr::select(Package, Version, date)
}


updates_select <- map_dfr(updates_list, select_pkg_ver_date)


first_relase <- updates_select %>% 
  group_by(Package) %>% 
  summarise(first = min(date)) %>% 
  rename(package = Package)

first_relase <- first_relase %>% 
  mutate(first = lubridate::as_date(first))
```




```{r}
download_2021 <- cran_logs %>% 
  filter(file_date >= "2021-01-01" & file_date <= "2021-12-31") %>%
  group_by(file_date,package) %>% 
  summarise(download = sum(n_total),unique = sum(n_unique)) %>% 
  collect()

#saveRDS(download_2021,file = "../data/analysis/download_2021.rds")
                                                                                  
total_2021_pkg <- download_2021 %>% 
  group_by(package) %>% 
  summarise(annual_total = sum(download), annual_unique =   sum(unique)) %>% 
  mutate(annual_total = as.integer(annual_total),
         annual_unique = as.integer(annual_unique))

total_2021_pkg <- total_2021_pkg %>% 
  left_join(first_relase, key = "package") %>% 
  filter(first <= "2021-01-01") 

total_2021_pkg <- total_2021_pkg %>% 
  mutate(diff = annual_total - annual_unique) %>% 
  mutate(precentage = (annual_unique/annual_total)*100)

```


```{r}
# ggplot has the most duplicated downloads in 2021
total_2021_pkg <- total_2021_pkg %>% 
  arrange(-annual_total) %>% 
  mutate(rank_total = rep(1:nrow(total_2021_pkg)))

total_2021_pkg <- total_2021_pkg %>% 
  arrange(-annual_unique) %>% 
  mutate(rank_unique = rep(1:nrow(total_2021_pkg))) %>% 
  mutate(rank_diff = rank_total - rank_unique) 

saveRDS(total_2021_pkg,file = "../data/analysis/total_2021_pkg.rds")

```

```{r}
total_2021_pkg %>% 
  ggplot(aes(x=precentage))+
  geom_histogram()
```


```{r}
download_2020 <- cran_logs %>% 
  filter(file_date >= "2020-01-01" & file_date <= "2020-12-31") %>%
  group_by(file_date,package) %>% 
  summarise(download = sum(n_total),unique = sum(n_unique)) %>% 
  collect()

saveRDS(download_2020,file = "../data/analysis/download_2020.rds")

download_2019 <- cran_logs %>% 
  filter(file_date >= "2019-01-01" & file_date <= "2019-12-31") %>%
  group_by(file_date,package) %>% 
  summarise(download = sum(n_total),unique = sum(n_unique)) %>% 
  collect()

saveRDS(download_2019,file = "../data/analysis/download_2019.rds")

download_2018 <- cran_logs %>% 
  filter(file_date >= "2018-01-01" & file_date <= "2018-12-31") %>%
  group_by(file_date,package) %>% 
  summarise(download = sum(n_total),unique = sum(n_unique)) %>% 
  collect()

saveRDS(download_2018,file = "../data/analysis/download_2018.rds")

download_2017 <- cran_logs %>% 
  filter(file_date >= "2017-01-01" & file_date <= "2017-12-31") %>%
  group_by(file_date,package) %>% 
  summarise(download = sum(n_total),unique = sum(n_unique)) %>% 
  collect()

saveRDS(download_2017,file = "../data/analysis/download_2017.rds")


download_2016 <- cran_logs %>% 
  filter(file_date >= "2016-01-01" & file_date <= "2016-12-31") %>%
  group_by(file_date,package) %>% 
  summarise(download = sum(n_total),unique = sum(n_unique)) %>% 
  collect()

saveRDS(download_2016,file = "../data/analysis/download_2016.rds")


download_2015 <- cran_logs %>% 
  filter(file_date >= "2015-01-01" & file_date <= "2015-12-31") %>%
  group_by(file_date,package) %>% 
  summarise(download = sum(n_total),unique = sum(n_unique)) %>% 
  collect()

saveRDS(download_2015,file = "../data/analysis/download_2015.rds")

download_2014 <- cran_logs %>% 
  filter(file_date >= "2014-01-01" & file_date <= "2014-12-31") %>%
  group_by(file_date,package) %>% 
  summarise(download = sum(n_total),unique = sum(n_unique)) %>% 
  collect()

saveRDS(download_2014,file = "../data/analysis/download_2014.rds")

download_2013 <- cran_logs %>% 
  filter(file_date >= "2013-01-01" & file_date <= "2013-12-31") %>%
  group_by(file_date,package) %>% 
  summarise(download = sum(n_total),unique = sum(n_unique)) %>% 
  collect()

saveRDS(download_2013,file = "../data/analysis/download_2013.rds")


```


```{r}

download_2020 <- readRDS("../data/analysis/download_2020.rds")

total_2020_pkg <- download_2020 %>% 
  group_by(package) %>% 
  summarise(annual_total = sum(download), annual_unique = sum(unique)) %>% 
  mutate(annual_total = as.integer(annual_total),
         annual_unique = as.integer(annual_unique))

total_2020_pkg <- total_2020_pkg %>% 
  mutate(diff = annual_total - annual_unique) %>% 
  mutate(precentage = (annual_unique/annual_total)*100)

total_2020_pkg <- total_2020_pkg %>% 
  arrange(-annual_total) %>% 
  mutate(rank_total = rep(1:nrow(total_2020_pkg)))

total_2020_pkg <- total_2020_pkg %>% 
  arrange(-annual_unique) %>% 
  mutate(rank_unique = rep(1:nrow(total_2020_pkg))) %>% 
  mutate(rank_diff = rank_total - rank_unique) 

total_2020_pkg <- total_2020_pkg %>% 
  left_join(first_relase, key = "package") %>% 
  filter(first <= "2020-01-01")

saveRDS(total_2020_pkg,file = "../data/analysis/total_2020_pkg.rds")


```

```{r}
download_2019 <- readRDS("../data/analysis/download_2019.rds")

total_2019_pkg <-download_2019 %>% 
  group_by(package) %>% 
  summarise(annual_total = sum(download), annual_unique = sum(unique)) %>% 
  mutate(annual_total = as.integer(annual_total),
         annual_unique = as.integer(annual_unique))

total_2019_pkg <- total_2019_pkg %>% 
  mutate(diff = annual_total - annual_unique) %>% 
  mutate(precentage = (annual_unique/annual_total)*100)

total_2019_pkg <- total_2019_pkg %>% 
  arrange(-annual_total) %>% 
  mutate(rank_total = rep(1:nrow(total_2019_pkg)))

total_2019_pkg <- total_2019_pkg %>% 
  arrange(-annual_unique) %>% 
  mutate(rank_unique = rep(1:nrow(total_2019_pkg))) %>% 
  mutate(rank_diff = rank_total - rank_unique)


total_2019_pkg <- total_2019_pkg %>% 
  left_join(first_relase, key = "package") %>% 
  filter(first <= "2019-01-01")

saveRDS(total_2019_pkg,file = "../data/analysis/total_2019_pkg.rds")

```


```{r}
download_2018 <- readRDS("../data/analysis/download_2018.rds")

total_2018_pkg <- download_2018 %>% 
  group_by(package) %>% 
  summarise(annual_total = sum(download), annual_unique = sum(unique)) %>% 
  mutate(annual_total = as.integer(annual_total),
         annual_unique = as.integer(annual_unique))

total_2018_pkg <- total_2018_pkg %>% 
  mutate(diff = annual_total - annual_unique) %>% 
  mutate(precentage = (annual_unique/annual_total)*100)

total_2018_pkg <- total_2018_pkg %>% 
  arrange(-annual_total) %>% 
  mutate(rank_total = rep(1:nrow(total_2018_pkg)))

total_2018_pkg <- total_2018_pkg %>% 
  arrange(-annual_unique) %>% 
  mutate(rank_unique = rep(1:nrow(total_2018_pkg))) %>% 
  mutate(rank_diff = rank_total - rank_unique)

total_2018_pkg <- total_2018_pkg %>% 
left_join(first_relase, key = "package") %>% 
  filter(first <= "2018-01-01")

saveRDS(total_2018_pkg,file = "../data/analysis/total_2018_pkg.rds")
```



```{r}

download_2017 <- readRDS("../data/analysis/download_2017.rds")

total_2017_pkg <-download_2017 %>% 
  group_by(package) %>% 
  summarise(annual_total = sum(download), annual_unique = sum(unique)) %>% 
  mutate(annual_total = as.integer(annual_total),
         annual_unique = as.integer(annual_unique))

total_2017_pkg <- total_2017_pkg %>% 
  mutate(diff = annual_total - annual_unique) %>% 
  mutate(precentage = (annual_unique/annual_total)*100)

total_2017_pkg <- total_2017_pkg %>% 
  arrange(-annual_total) %>% 
  mutate(rank_total = rep(1:nrow(total_2017_pkg)))

total_2017_pkg <- total_2017_pkg %>% 
  arrange(-annual_unique) %>% 
  mutate(rank_unique = rep(1:nrow(total_2017_pkg))) %>% 
  mutate(rank_diff = rank_total - rank_unique)

total_2017_pkg <- total_2017_pkg %>% 
  left_join(first_relase, key = "package") %>% 
  filter(first <= "2017-01-01")

saveRDS(total_2017_pkg,file = "../data/analysis/total_2017_pkg.rds")

```

```{r}
download_2016 <- readRDS("../data/analysis/download_2016.rds")

total_2016_pkg <-download_2016 %>% 
  group_by(package) %>% 
  summarise(annual_total = sum(download), annual_unique = sum(unique)) %>% 
  mutate(annual_total = as.integer(annual_total),
         annual_unique = as.integer(annual_unique))

total_2016_pkg <- total_2016_pkg %>% 
  mutate(diff = annual_total - annual_unique) %>% 
  mutate(precentage = (annual_unique/annual_total)*100)

total_2016_pkg <- total_2016_pkg %>% 
  arrange(-annual_total) %>% 
  mutate(rank_total = rep(1:nrow(total_2016_pkg)))

total_2016_pkg <- total_2016_pkg %>% 
  arrange(-annual_unique) %>% 
  mutate(rank_unique = rep(1:nrow(total_2016_pkg))) %>% 
  mutate(rank_diff = rank_total - rank_unique)

total_2016_pkg <- total_2016_pkg %>% 
left_join(first_relase, key = "package") %>% 
  filter(first <= "2016-01-01")

saveRDS(total_2016_pkg,file = "../data/analysis/total_2016_pkg.rds")
```


```{r}
download_2015 <- readRDS("../data/analysis/download_2015.rds")

total_2015_pkg <-download_2015 %>% 
  group_by(package) %>% 
  summarise(annual_total = sum(download), annual_unique = sum(unique)) %>% 
  mutate(annual_total = as.integer(annual_total),
         annual_unique = as.integer(annual_unique))

total_2015_pkg <- total_2015_pkg %>% 
  mutate(diff = annual_total - annual_unique) %>% 
  mutate(precentage = (annual_unique/annual_total)*100)

total_2015_pkg <- total_2015_pkg %>% 
  arrange(-annual_total) %>% 
  mutate(rank_total = rep(1:nrow(total_2015_pkg)))

total_2015_pkg <- total_2015_pkg %>% 
  arrange(-annual_unique) %>% 
  mutate(rank_unique = rep(1:nrow(total_2015_pkg))) %>% 
  mutate(rank_diff = rank_total - rank_unique)

total_2015_pkg <- total_2015_pkg %>% 
left_join(first_relase, key = "package") %>% 
  filter(first <= "2015-01-01")

saveRDS(total_2015_pkg,file = "../data/analysis/total_2015_pkg.rds")

```


```{r}
download_2014 <- readRDS("../data/analysis/download_2014.rds")

total_2014_pkg <-download_2014 %>% 
  group_by(package) %>% 
  summarise(annual_total = sum(download), annual_unique = sum(unique)) %>% 
  mutate(annual_total = as.integer(annual_total),
         annual_unique = as.integer(annual_unique))

total_2014_pkg <- total_2014_pkg %>% 
  mutate(diff = annual_total - annual_unique) %>% 
  mutate(precentage = (annual_unique/annual_total)*100)

total_2014_pkg <- total_2014_pkg %>% 
  arrange(-annual_total) %>% 
  mutate(rank_total = rep(1:nrow(total_2014_pkg)))

total_2014_pkg <- total_2014_pkg %>% 
  arrange(-annual_unique) %>% 
  mutate(rank_unique = rep(1:nrow(total_2014_pkg))) %>% 
  mutate(rank_diff = rank_total - rank_unique)

total_2014_pkg <- total_2014_pkg %>% 
left_join(first_relase, key = "package") %>% 
  filter(first <= "2014-01-01")

saveRDS(total_2014_pkg,file = "../data/analysis/total_2014_pkg.rds")

```

```{r}
download_2013 <- readRDS("../data/analysis/download_2013.rds")

total_2013_pkg <-download_2013 %>% 
  group_by(package) %>% 
  summarise(annual_total = sum(download), annual_unique = sum(unique)) %>% 
  mutate(annual_total = as.integer(annual_total),
         annual_unique = as.integer(annual_unique))

total_2013_pkg <- total_2013_pkg %>% 
  mutate(diff = annual_total - annual_unique) %>% 
  mutate(precentage = (annual_unique/annual_total)*100)

total_2013_pkg <- total_2013_pkg %>% 
  arrange(-annual_total) %>% 
  mutate(rank_total = rep(1:nrow(total_2013_pkg)))

total_2013_pkg <- total_2013_pkg %>% 
  arrange(-annual_unique) %>% 
  mutate(rank_unique = rep(1:nrow(total_2013_pkg))) %>% 
  mutate(rank_diff = rank_total - rank_unique)

total_2013_pkg <- total_2013_pkg %>% 
left_join(first_relase, key = "package") %>% 
  filter(first <= "2013-01-01")

saveRDS(total_2013_pkg,file = "../data/analysis/total_2013_pkg.rds")

```


```{r}
total_2013_pkg <- readRDS("../data/analysis/total_2013_pkg.rds")
total_2014_pkg <- readRDS("../data/analysis/total_2014_pkg.rds")
total_2015_pkg <- readRDS("../data/analysis/total_2015_pkg.rds")
total_2016_pkg <- readRDS("../data/analysis/total_2016_pkg.rds")
total_2017_pkg <- readRDS("../data/analysis/total_2017_pkg.rds")
total_2018_pkg <- readRDS("../data/analysis/total_2018_pkg.rds")
total_2019_pkg <- readRDS("../data/analysis/total_2019_pkg.rds")
total_2020_pkg <- readRDS("../data/analysis/total_2020_pkg.rds")
total_2021_pkg <- readRDS("../data/analysis/total_2021_pkg.rds")


total_year <- bind_rows(
  `2013`= total_2013_pkg,
  `2014`= total_2014_pkg,
  `2015`= total_2015_pkg,
  `2016`= total_2016_pkg,
  `2017`= total_2017_pkg,
  `2018`= total_2018_pkg,
  `2019`= total_2019_pkg,
  `2020`= total_2020_pkg,
  `2021`= total_2021_pkg,
  .id = "year"
)

saveRDS(total_year,file = "../data/analysis/total_year.rds")
```

```{r}
total_year %>% ggplot(aes(y = precentage, x = year)) +
  geom_violin() + 
  geom_boxplot(width = 0.1) 
```

```{r}
library(plotly)

total_year %>% 
  filter(rank_unique <= 10) %>% 
  ggplot(aes(y = precentage, x = year, color = year, text = package)) + 
  geom_point()

ggplotly()
```


```{r}
pkgs_big_rank_diff <- total_year %>% 
  filter(rank_diff < 0 ) %>% 
  filter(rank_total < 50) %>% 
  group_by(package) %>% 
  summarise(rank_diff = sum(abs(rank_diff)),
            n = n()) %>% 
  filter(n > 3) %>% 
  arrange(desc(rank_diff)) %>% 
  slice(1:40) %>% 
  pull(package) 

total_year %>% 
  #filter(package %in% c("ggplot2","dplyr","tibble","RColorBrewer","rlang", "colorspace", "tidyr", "lme4", "agricolae")) %>% 
  filter(package %in% pkgs_big_rank_diff) %>% 
  ggplot(aes(x=year))+
  geom_line(aes(y = rank_unique, group = package), color = "red") +
  geom_line(aes(y = rank_total, group = package), color = "black") + 
  facet_wrap(~package, scale = "free")
```

```{r}
pkgs_big_rank_diff <- total_year %>% 
  filter(rank_diff < 0 ) %>% 
  filter(rank_total < 20) %>% 
  group_by(package) %>% 
  summarise(rank_diff = sum(abs(rank_diff)),
            n = n()) %>% 
  filter(n > 3) %>% 
  arrange(desc(rank_diff)) %>% 
  slice(1:40) %>% 
  pull(package) 

total_year %>% 
  #filter(package %in% c("ggplot2","dplyr","tibble","RColorBrewer","rlang", "colorspace", "tidyr", "lme4", "agricolae")) %>% 
  filter(package %in% pkgs_big_rank_diff) %>% 
  ggplot(aes(x=year))+
  geom_line(aes(y = rank_unique, group = package), color = "red") +
  geom_line(aes(y = rank_total, group = package), color = "black") + 
  facet_wrap(~package, scale = "free")
```


```{r}
total_year %>% 
  group_by(year) %>% 
  top_n(10, rank_total)  %>% 
  ggplot(aes(y = precentage, x = year, color = year, text = package)) + 
  geom_point()

ggplotly()
```



