---
title: "analysis_plots"
author: "Danyang Dai"
date: "07/06/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(cranlogs)
library(broom)
```

```{r}
years <- 2013:2021
totals_df <- map_dfr(years,
                   ~{
                     readRDS(glue::glue("../data/analysis/total_{.x}_pkg.rds")) %>% 
                               arrange(desc(annual_total)) %>% 
                               mutate(rank_total = 1:n(),
                                      age = year(Sys.Date()) - year(first),
                                      year = .x) 
                    })
```




```{r}
total_2021_pkg %>% 
 # top_n(100, annual_total) %>% 
  ggplot(aes(x = log(annual_total))) + 
  geom_point(aes(y = precentage, color = years))
```

```{r}
total_2020_pkg <- total_2020_pkg %>% 
  mutate(years = format(first, format = "%Y")) 

total_2020_pkg <- total_2020_pkg %>% 
  mutate(years = 2021- as.integer(years))

total_2020_pkg %>% 
 # top_n(100, annual_total) %>% 
  ggplot(aes(x = log(annual_total))) + 
  geom_point(aes(y = precentage, color = years))
```


```{r}
total_2015_pkg <- total_2015_pkg %>% 
  mutate(years = format(first, format = "%Y")) 

total_2015_pkg <- total_2015_pkg %>% 
  mutate(years = 2016- as.integer(years))

total_2015_pkg %>% 
 # top_n(100, annual_total) %>% 
  ggplot(aes(x = log(annual_total))) + 
  geom_point(aes(y = precentage, color = years))
```


```{r}
total_year <- total_year %>% 
  mutate(years = format(first, format = "%Y")) 


total_year %>% 
  ggplot(aes(x = annual_unique, y = annual_total)) + 
  #geom_point(aes(y = precentage)) +
  geom_point() + 
  #geom_abline(slope = 1, intercept = 0, color = "red") +
  geom_smooth(method = MASS::rlm) +
  facet_wrap(~year, scale = "free") 

```


```{r}
linear_model <- total_dfs %>% 
  group_by(year) %>% 
  nest() %>% 
  mutate(model = map(data, ~MASS::rlm(annual_total ~ annual_unique, data = .x)),
         coeff = map(model, ~tidy(.x)),
         resid = map(model, ~augment(.x)),
         package = map(data, ~select(.x, package)))

redis_plot <- linear_model %>% 
  select(year, resid) %>% 
  unnest(resid)

redis_plot %>% 
   ggplot(aes(x = .fitted,
           y = .resid)) +
  geom_point() +
  geom_hline(yintercept = 0, colour = "red") + 
  facet_wrap(~year, scales = "free")
```

```{r}
redis_plot %>% 
   ggplot(aes(x = .fitted,
           y = .resid, color= year)) +
  geom_point(alpha = 0.3) +
  geom_hline(yintercept = 0, colour = "red") 
```


```{r}
large_redis <- redis_plot %>% 
  filter(.resid >= 10000 | .resid <= -10000) 

large_redis %>% 
  mutate(value = ifelse(.resid >0, "Positive", "Negative")) %>% 
  ggplot(aes(x = year, fill = value)) +
  geom_bar(stat = "count") 
  
```

```{r}
large_redis_pkg <- large_redis %>% 
  unnest(data)
```

```{r}
coeff_plots <- linear_model %>% 
  unnest(coeff) %>% 
  select(year, term, estimate)

coeff_plots <- coeff_plots %>% 
   pivot_wider(id_cols = year, names_from =  term, values_from = estimate) %>%
   rename(intercept = `(Intercept)`,
          coeff = `x$annual_unique`)

coeff_plots %>% 
  ggplot(aes(x = year, 
                y = intercept, 
                colour = coeff, 
                label = year)) +
  geom_point() 
```


```{r}
coeff_plots %>% 
  ggplot(aes(x = year, 
                y = coeff, 
                colour = intercept, 
                label = year)) +
  geom_point(size = 2)+
  geom_line(group = 1)
```

```{r}

linear_model <- linear_model %>% 
  mutate(model_wo = lapply(data, function(x) lm(x$annual_total ~ x$annual_unique + 0)))

linear_model <- linear_model %>% 
  mutate(coeff_wo = lapply(model_wo, function(x) tidy(x))) %>% 
  mutate(redis_wo = lapply(model_wo, function(x) augment(x)))

redis_plot_wo <- linear_model %>% 
  unnest(redis_wo)

redis_plot_wo %>% 
   ggplot(aes(x = .fitted,
           y = .resid)) +
  geom_point() +
  geom_hline(yintercept = 0, colour = "red") + 
  facet_wrap(~year)
```

```{r}
coeff_plots_wo <- linear_model %>% 
  unnest(coeff_wo) %>% 
  select(year, term, estimate)

coeff_plots_wo <- coeff_plots_wo %>% 
   pivot_wider(id_cols = year, names_from =  term, values_from = estimate) %>%
   rename(coeff = `x$annual_unique`)

coeff_plots_wo %>% 
  ggplot(aes(x = year, 
                y = coeff, 
                label = year)) +
  geom_point(size = 2)+
  geom_line(group = 1)
```
```{r}
large_redis_wo <- redis_plot_wo %>% 
  filter(.resid >= 10000 | .resid <= -10000) 

large_redis_wo %>% 
  mutate(value = ifelse(.resid >0, "Positive", "Negative")) %>% 
  ggplot(aes(x = year, fill = value)) +
  geom_bar(stat = "count") 
```

```{r}
redis_plot_wo <- redis_plot_wo %>% 
  rename(annual_total = `x$annual_total`) %>% 
  left_join(total_year)

ggplot(data = total_year, 
       aes(x = annual_unique, y = annual_total)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method="lm",formula = y ~ 0 + x, se = FALSE) +
  # overlay fitted values
  geom_point(data = redis_plot_wo, 
             aes(y = .fitted), 
             color = "blue", 
             alpha = 0.2) +
  # draw a line segment from the fitted value to observed value
  geom_segment(data = redis_plot_wo, 
               aes(y = .fitted, xend = annual_unique, yend = annual_total),
               color = "blue",
               alpha = 0.2) + 
  facet_wrap(~year)
```

```{r}
total_year <- total_year %>% 
  arrange(-annual_total) %>% 
  mutate(rank_total = rep(1:nrow(total_year)))

total_year <- total_year %>% 
  mutate(years = format(first, format = "%Y")) 

total_year <- total_year %>% 
  mutate(years = 2022- as.integer(years))
```

```{r}
total_year %>% 
  ggplot(aes(x = years)) + 
  geom_point(aes(y = diff)) +
  geom_tile("annual total - annual unique and no. years of release")
```

```{r}
total_year %>% 
  ggplot(aes(x = years, y = precentage, group  = years)) + 
  geom_violin() + 
  geom_boxplot(width = 0.1) + 
  scale_x_reverse()+
  facet_wrap(~year) + 
  xlab("Age of the packages") + 
  ylab("total unique / total total")
```


```{r}
total_year %>% 
  filter(rank_unique <= 50 ) %>% 
  ggplot(aes(x = year)) + 
  geom_boxplot(aes(y = rank_diff))# + 
  #ylim(-500,100)
```
```{r}
total_year %>% 
  filter(rank_unique <= 50 ) %>% 
  ggplot(aes(x = year)) + 
  geom_boxplot(aes(y = abs(rank_diff))) + 
  ylab("absulate value of (rank total - rank unique) ") +
  xlab("Year")
```


```{r}
total_year %>% 
  filter(rank_unique <= 10) %>% 
  ggplot(aes(y = precentage, x = year, color = year, text = package)) + 
  geom_point()
```

```{r}
total_year %>% 
  ggplot(aes(y = precentage, x = year)) +
  geom_violin() + 
  geom_boxplot(width = 0.1) 
```

```{r}
pkgs_big_rank_diff <- total_year %>% 
  filter(rank_diff > 0 ) %>% 
  filter(rank_total < 50) %>% 
  group_by(package) %>% 
  summarise(rank_diff = sum(abs(rank_diff)),
            n = n()) %>% 
  filter(n > 3) %>% 
  arrange(desc(rank_diff)) %>% 
  slice(1:40) %>% 
  pull(package) 

total_year %>% 
  filter(package %in% pkgs_big_rank_diff) %>% 
  ggplot(aes(x=year))+
  geom_line(aes(y = rank_unique, group = package), color = "red") +
  geom_line(aes(y = rank_total, group = package), color = "black") + 
  facet_wrap(~package, scale = "free") + 
  scale_y_reverse()
```

```{r}
pkgs_big_rank_diff_neg <- total_year %>% 
  filter(rank_diff < 0 ) %>% 
  filter(rank_total < 50) %>% 
  group_by(package) %>% 
  summarise(rank_diff = sum(abs(rank_diff)),
            n = n()) %>% 
  filter(n > 3) %>% 
  arrange(desc(rank_diff)) %>% 
  slice(1:40) %>% 
  pull(package) 

total_year %>% 
  filter(package %in% pkgs_big_rank_diff_neg) %>% 
  ggplot(aes(x=year))+
  geom_line(aes(y = rank_unique, group = package), color = "red") +
  geom_line(aes(y = rank_total, group = package), color = "black") + 
  facet_wrap(~package, scale = "free") + 
  scale_y_reverse()
```

```{r}
# top packages
total_year %>% 
  filter(rank_total <= 50) %>% 
  ggplot(aes(x = year, y = rank_diff, group = year)) + 
  geom_violin() + 
  geom_boxplot(width = 0.1) 
```

```{r}
# bottom 50 packages 
total_year %>% 
  group_by(year) %>%
  arrange(rank_total) %>%
  slice(1:50) %>%
  ungroup() %>% 
  ggplot(aes(x = year, y = rank_diff, group = year)) + 
  geom_violin() + 
  geom_boxplot(width = 0.1) 
```

```{r}
no_updates <- updates_select %>% 
  group_by(Package) %>% 
  count() %>% 
  mutate(package = as.character(Package), 
         no_updates = as.integer(n)) %>% 
  select(package, no_updates)

total_year <- total_year %>% 
  left_join(no_updates)
```

```{r}
total_year %>% 
  #filter(rank_total <= 50) %>% 
  ggplot(aes(x = no_updates, color = annual_total)) + 
  geom_point(aes(y = precentage))# + 
 # facet_wrap(~year)
```
```{r}
total_year %>% 
  ggplot(aes(x = no_updates)) + 
  geom_point(aes(y = precentage, colour = log(annual_total))) +
  facet_wrap(~year)
```

```{r}
total_year %>% 
  ggplot(aes(x = no_updates)) + 
  geom_point(aes(y = log(annual_total)))
```

```{r}
total_year %>% 
  ggplot(aes(x = no_updates)) + 
  geom_point(aes(y = rank_diff), alpha = 0.05) 
```


```{r}
library(cranlogs)
cran_downloads("nestr",from = "2022-05-31", to = "2022-06-06")

```

```{r}
# start <- as.Date('2022-05-31')
# end <- as.Date('2022-06-06')
# all_days <- seq(start, end, by = 'day')
# year <- as.POSIXlt(all_days)$year + 1900
# urls <- paste0('http://cran-logs.rstudio.com/', year, '/', all_days, '.csv.gz')
# nestr_1 <- read_csv(urls[1])
# nestr_2 <- read_csv(urls[2])
# nestr_3 <- read_csv(urls[3])
# nestr_4 <- read_csv(urls[4])
# nestr_5 <- read_csv(urls[5])
# nestr_6 <- read_csv(urls[6])
# nestr_7 <- read_csv(urls[7])

```

```{r}
# saveRDS(nestr_1,file = "../data/analysis/cranlog_2022-05-31.rds")
# saveRDS(nestr_2,file = "../data/analysis/cranlog_2022-06-01.rds")
# saveRDS(nestr_3,file = "../data/analysis/cranlog_2022-06-02.rds")
# saveRDS(nestr_4,file = "../data/analysis/cranlog_2022-06-03.rds")
# saveRDS(nestr_5,file = "../data/analysis/cranlog_2022-06-04.rds")
# saveRDS(nestr_6,file = "../data/analysis/cranlog_2022-06-05.rds")
# saveRDS(nestr_7,file = "../data/analysis/cranlog_2022-06-06.rds")

nestr_1 <- readRDS(file = "../data/analysis/cranlog_2022-05-31.rds")
nestr_2 <- readRDS(file = "../data/analysis/cranlog_2022-06-01.rds")
nestr_3 <- readRDS(file = "../data/analysis/cranlog_2022-06-02.rds")
nestr_4 <- readRDS(file = "../data/analysis/cranlog_2022-06-03.rds")
nestr_5 <- readRDS(file = "../data/analysis/cranlog_2022-06-04.rds")
nestr_6 <- readRDS(file = "../data/analysis/cranlog_2022-06-05.rds")
nestr_7 <- readRDS(file = "../data/analysis/cranlog_2022-06-06.rds")


```

```{r}
nestr_1 <- nestr_1 %>% 
  filter(package == "nestr")

nestr_2 <- nestr_2 %>% 
  filter(package == "nestr")

nestr_3 <- nestr_3 %>% 
  filter(package == "nestr")

nestr_4 <- nestr_4 %>% 
  filter(package == "nestr")

nestr_5 <- nestr_5 %>% 
  filter(package == "nestr")

nestr_6 <- nestr_6 %>% 
  filter(package == "nestr")

nestr_7 <- nestr_7 %>% 
  filter(package == "nestr")
```

```{r}
unique_count <- function(cranlog_files){
  cranlog_files %>% 
  count(date, r_version, r_arch, r_os, package, version, country, ip_id) %>% 
      group_by(date, package) %>% 
      summarise(n_unique = n(), n_total = sum(n), .groups = "drop")
  }
```

```{r}
unique_count(nestr_1)
unique_count(nestr_2)
unique_count(nestr_6)

```

