---
title: "R package downloads: what does it mean?"
author:
  # Dai Dai to add her own name here
  - name: Danyang Dai
  - name: Emi Tanaka
    affiliation: Monash University
    address:
    - Monash University
    - Clayton campus, VIC 3800, Australia
    url: http://emitanaka.org/
    orcid: 0000-0002-1455-259X
    email:  emi.tanaka@monash.edu
abstract: >
    Abstract
bibliography: paper.bib

output: 
  bookdown::html_document2:
    theme: paper
---

```{r setup, cache = FALSE, include = FALSE}
library(tidyverse)
tocache <- TRUE
knitr::opts_chunk$set(echo = FALSE, 
                      cache = TRUE,
                      cache.path = "cache/",
                      fig.align = 'center', 
                      fig.pos = 'htbp', 
                      fig.width = 6,
                      message = FALSE,
                      warning = FALSE)

theme_set(
  theme(panel.background = element_rect(fill = NA),
        panel.grid = element_line(color = "lightgray"),
        axis.text = element_text(color = "black"),
        axis.line = element_line(color = "black", size = 0.7),
        axis.ticks.length = unit(1.4, "mm"),
        axis.ticks = element_line(color = "black", size = 0.7),
        axis.title = element_text(color = "black", face = "bold"),
        strip.background = element_rect(color = "black",
                                        fill = "black"),
        strip.text = element_text(color = "white"),
        plot.title.position = "plot",
        plot.title = element_text(color = "black", hjust = 0)))
```

# Introduction

Since R was first introduced in the August of 1993 with its first official release in the June of 1995 [@ihaka:1996], there was only a small group of core developers. In April of 1997, the Comprehensive R Archive Network (CRAN) was established as the official R-packages repository, with 3 mirror sites. In June 2010, there are 2417 packages from CRAN [@Theu]. In March 2015, there are 6411 packages on CRAN [@DecanAlexandre2015OtDa]. After years of continues thrive of R packages developments, today R is greatly enhanced by over 17 thousands (17481, from the latest cran-name scrap) R-packages contributed by 15112 (number from removing the same authors in the db dataset) of developers all over the world. The source repositories to install R-packages have expanded to Bioconductor, Gitlab, GitHub, R-Forge and 106 CRAN mirrors in 49 regions. Of all the CRAN mirrors, the daily download counts for each package is only readily available from the RStudio CRAN mirror. This is also the default CRAN mirror if not deliberately chosen a CRAN mirror in RStudio [@rstudiocran]. The RStudio CRAN mirror is likely to have the most users as the default mirror for R users. 



# Data

The main source of data used in this report is the download logs from the RStudio CRAN mirror site : https://cran.rstudio.com/. These log files are created for every instance of download of an R-package via the RStudio CRAN mirror, then these log files are processed, daily, into CSV files that contain the following variables with the name of header in brackets:

* Date (`date`),
* Time in UTC time zone (`time`),
* Size of the file in bytes  (`size`),
* Version of R used to download the package (`r_version`),
* Architecture type for R (i386 = 32 bit, x86_64 = 64 bit) (`r_arch`),
* Operating System (darwin9.8.0 = mac, mingw32 = windows) (`r_os`),
* Package (`package`),
* Country in two letter ISO country code (`country`), and
* Anonymised daily unique id (`ip_id`).

A similar log file is also created for every download of R from the RStudio CRAN mirror with the processed log file generating a CSV file that contains the same variables except `r_arch` and `package`, and `r_version` and `r_os` are named as `version` and `os`. These CSV files are hosted at http://cran-logs.rstudio.com/ and updated daily with data available from 1st October 2012. 

The log files of a particular day is processed and compressed into a single CSV file of about 40 megabytes (file sizes of earlier years are much smaller due to lower number of download logs). As there are over 700,000 CSV files, a simple estimate of the size of the data is 28 terabytes - far exceeding typical portable hard drives which are 1-4 terabytes. 

The summarised version of data, where the data show the total daily download counts for each package, is accessible using the `cranlogs` R-package. The `cranlogs` package accesses this summary data through the web application programming interface (API) maintained by r-hub [@rhub].


# Results

# Discussion

